[package]
name = "droxy"
version = "0.1.0"
authors = ["diract"]

[dependencies]
bytes = "0.4"
futures = "0.1"
tokio-io = "0.1"
tokio-core = "0.1"
tokio-proto = "0.1"
tokio-service = "0.1"
radix_trie = "0.1.*"
treebitmap = "0.2.2"

