[package]
name = "droxy"
version = "0.1.0"
authors = ["diract"]

[dependencies]
bytes = "0.4"
error-chain = "0.11.0"
futures = "0.1"
futures-cpupool = "0.1"
log = "0.3.5"
tokio-io = "0.1"
tokio-core = "0.1"
tokio-proto = "0.1"
tokio-service = "0.1"
tokio-timer = "0.1"
radix_trie = "0.1.*"
treebitmap = { path="../treebitmap" }
trust-dns-server = "0.12.0"
trust-dns = "0.12.0"

